import{useEffect,useRef,useState}from'react';
type Status='idle'|'connecting'|'listening'|'translating'|'error';
type Token={token:string;expiresAt:number;endpoint:string};
type Event={type:string;delta?:string;transcript?:string;error?:{message?:string}};
const languages=['auto','Arabic','French','German','Hindi','Italian','Japanese','Korean','Mandarin Chinese','Portuguese','Spanish','Tamil'];
export default function App(){
 const[status,setStatus]=useState<Status>('idle'),[language,setLanguage]=useState('auto'),[transcript,setTranscript]=useState(''),[partial,setPartial]=useState(''),[error,setError]=useState('');
 const peer=useRef<RTCPeerConnection|null>(null),media=useRef<MediaStream|null>(null),channel=useRef<RTCDataChannel|null>(null),audio=useRef<HTMLAudioElement>(null),partialRef=useRef('');
 const stop=()=>{channel.current?.close();peer.current?.close();media.current?.getTracks().forEach(t=>t.stop());channel.current=null;peer.current=null;media.current=null;if(audio.current)audio.current.srcObject=null;setStatus('idle');setPartial('');partialRef.current=''};
 useEffect(()=>stop,[]);
 const onEvent=(raw:MessageEvent<string>)=>{const e=JSON.parse(raw.data)as Event;if(e.type==='input_audio_buffer.speech_started')setStatus('translating');if(e.type==='input_audio_buffer.speech_stopped')setStatus('listening');if(e.type==='response.output_audio_transcript.delta'||e.type==='response.output_text.delta'){partialRef.current+=e.delta??'';setPartial(partialRef.current)}if(e.type==='response.output_audio_transcript.done'||e.type==='response.output_text.done'){const text=e.transcript||partialRef.current;if(text)setTranscript(v=>v+(v?'\n':'')+text);partialRef.current='';setPartial('')}if(e.type==='error'||e.type==='session.error'){setError(e.error?.message||'Realtime session error.');setStatus('error')}};
 const start=async()=>{setStatus('connecting');setError('');setTranscript('');try{const response=await fetch('/api/realtime/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceLanguage:language,voice:'alloy'})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Could not create a session.');const session=body as Token;const pc=new RTCPeerConnection();peer.current=pc;pc.ontrack=e=>{if(audio.current)audio.current.srcObject=e.streams[0]};pc.onconnectionstatechange=()=>{if(pc.connectionState==='connected')setStatus('listening');if(['failed','disconnected'].includes(pc.connectionState)){setError('The audio connection was lost.');setStatus('error')}};const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});media.current=stream;stream.getTracks().forEach(t=>pc.addTrack(t,stream));const dc=pc.createDataChannel('realtime-channel');channel.current=dc;dc.onmessage=onEvent;const offer=await pc.createOffer();await pc.setLocalDescription(offer);const answer=await fetch(`${session.endpoint.replace(/\/$/,'')}/openai/v1/realtime/calls?webrtcfilter=on`,{method:'POST',body:offer.sdp,headers:{Authorization:`Bearer ${session.token}`,'Content-Type':'application/sdp'}});if(!answer.ok)throw new Error(`WebRTC negotiation failed (${answer.status}).`);await pc.setRemoteDescription({type:'answer',sdp:await answer.text()})}catch(cause){stop();setStatus('error');setError(cause instanceof Error?cause.message:'Unable to start.')}};
 const active=status==='listening'||status==='translating';
 return <main><audio ref={audio} autoPlay/><header><span className="mark">LI</span><span>Live Interpreter</span><span className="secure">Azure AI Foundry</span></header><section className="hero"><p className="eyebrow">REALTIME VOICE TRANSLATION</p><h1>Speak naturally.<br/><em>Hear it in English.</em></h1><p className="intro">Low-latency interpretation powered by GPT Realtime Translate. Microphone audio streams directly to Azure.</p></section><section className={`console ${active?'active':''}`}><div className="controls"><label>INPUT LANGUAGE<select disabled={status!=='idle'&&status!=='error'} value={language} onChange={e=>setLanguage(e.target.value)}>{languages.map(l=><option key={l} value={l}>{l==='auto'?'Auto detect':l}</option>)}</select></label><div className="arrow">→</div><label>OUTPUT LANGUAGE<div className="locked">English <span>LOCKED</span></div></label></div><div className="stage"><button className={`mic ${active?'live':''}`} onClick={active?stop:start} disabled={status==='connecting'}>{status==='connecting'?'···':active?'■':'●'}</button><h2>{status==='idle'?'Ready when you are':status==='connecting'?'Connecting securely…':status==='translating'?'Translating…':status==='error'?'Connection issue':'Listening…'}</h2><p>{active?'Speak naturally. Tap stop when finished.':'Tap the microphone and allow browser access.'}</p>{active&&<div className="wave">{Array.from({length:28},(_,i)=><i key={i} style={{animationDelay:`${i*-.07}s`}}/>)}</div>}</div>{(transcript||partial)&&<div className="transcript"><small>ENGLISH TRANSCRIPT</small><p>{transcript}{partial&&<><br/><span>{partial}</span></>}</p></div>}{error&&<div className="error">{error}</div>}</section><footer><span>WebRTC encrypted audio</span><span>•</span><span>English voice + transcript</span><span>•</span><span>Server-side credentials</span></footer></main>}
